image: registry.gitlab.com/harshithpabbati/webapp:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

pages:
  stage: deploy
  script:
    - npm install
    - npm run export
    - rm -rf public
    - mv out public

  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - master
